version: '2'
services:
    httpd:
        image: michzimny/apache-letsencrypt
        environment:
            - DOMAINS
            - WEBMASTER_MAIL
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./sites-enabled:/etc/apache2/sites-enabled"

